export const products = [
  {
    id: 1,
    src: "/cafe-expresso-tradicional.png",
    alt: "Icone com uma xícara de café expresso tradicional",
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 9.9,
    badges: ["Tradicional"],
  },
  {
    id: 2,
    src: "/cafe-expresso-americano.png",
    alt: "Ícone com uma xícara de expresso americano",
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 9.9,
    badges: ["Tradicional"],
  },
  {
    id: 3,
    src: "/cafe-expresso-cremoso.png",
    alt: "Icone com uma xícara de café expresso tradicional",
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: 9.9,
    badges: ["Tradicional"],
  },
  {
    id: 4,
    src: "/cafe-expresso-gelado.png",
    alt: "Icone com uma xícara de café expresso gelado",
    name: "Expresso Cremoso",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 9.9,
    badges: ["Tradicional", "Gelado"],
  },
  {
    id: 5,
    src: "/cafe-com-leite.png",
    alt: "Icone com uma xícara de café com leite",
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 9.9,
    badges: ["Tradicional", "Com leite"],
  },
  {
    id: 6,
    src: "/cafe-latte.png",
    alt: "Icone com uma xícara de café Latte",
    name: "Latte",
    description: "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: 9.9,
    badges: ["Tradicional", "Com leite"],
  },
  {
    id: 7,
    src: "/cafe-capuccino.png",
    alt: "Icone com uma xícara de café Capuccino",
    name: "Capuccino",
    description: "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 9.9,
    badges: ["Tradicional", "Com leite"],
  },
  {
    id: 8,
    src: "/cafe-macchiato.png",
    alt: "Icone com uma xícara de café Macchiato",
    name: "Macchiato",
    description: "Café expresso misturado com um pouco de leite quente e espuma",
    price: 9.9,
    badges: ["Tradicional", "Com leite"],
  },
  {
    id: 9,
    src: "/cafe-mocaccino.png",
    alt: "Icone com uma xícara de café Mocaccino",
    name: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 9.9,
    badges: ["Tradicional", "Com leite"],
  },
  {
    id: 10,
    src: "/chocolate-quente.png",
    alt: "Icone com uma xícara de chocolate quente",
    name: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 9.9,
    badges: ["Tradicional", "Com leite"],
  },
  {
    id: 11,
    src: "/cafe-cubano.png",
    alt: "Icone com uma xícara de café cubano",
    name: "Cubano",
    description: "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 9.9,
    badges: ["Tradicional", "Alcoólico", "Gelado"],
  },
  {
    id: 12,
    src: "/cafe-havaiano.png",
    alt: "Icone com uma xícara de café cubano",
    name: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 9.9,
    badges: ["Especial"],
  },
  {
    id: 13,
    src: "/cafe-arabe.png",
    alt: "Icone com uma xícara de café árabe",
    name: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 9.9,
    badges: ["Especial"],
  },
  {
    id: 14,
    src: "/cafe-irlandes.png",
    alt: "Icone com uma xícara de café Irlandês",
    name: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 9.9,
    badges: ["Especial", "Alcoólico"],
  },
];
